name: qcabs_driver
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.6+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dotted_border: ^2.0.0+2
  sizer: ^2.0.15
  http_parser: ^4.0.0
  font_awesome_flutter: ^9.2.0
  animated_widgets: ^1.1.0
  page_transition: ^2.0.4
  http: ^0.13.4
  dropdown_search: ^3.0.1
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.0
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.9
#  image_cropper: ^1.5.1
  shared_preferences: ^2.0.5
  provider: ^6.0.2
  #  charts_flutter: ^0.10.0
  cached_network_image: 
  animation_wrappers: ^0.0.4
  location: ^4.3.0
  geocoder: ^0.2.1
  google_maps_place_picker_mb: ^2.0.0-mb.16
  google_maps_flutter: ^2.0.6
  connectivity: ^3.0.6
  flutter_polyline_points: ^1.0.0
  google_mobile_ads: ^0.13.2
  equatable: ^2.0.3
  image_picker_gallery_camera: ^0.2.2
  flutter_local_notifications: ^9.0.0
  path_provider: ^2.0.2
  firebase_core: ^1.11.0
  firebase_messaging: ^10.0.4
  permission_handler: ^8.3.0
  social_share: ^2.2.1
  url_launcher: ^6.0.17
  awesome_notifications: ^0.6.21
  image_cropper: ^1.4.1
  screen: ^0.0.5
  animated_text_kit: ^4.2.2
  razorpay_flutter: ^1.2.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"

flutter_launcher_name:
  name: "sahayatri"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - lib/language/

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf